# docker-compose.yml文件的版本
version: "3"
# 管理的服务
services:
  redis:
    # 指定镜像
    image: redis:3
    ports:
      # 端口映射
      - 6379:6379
#    volumes:
#      - redis:/var/lib/redis
    command:
      # 执行的命令
      redis-server

  mysql:
    image: mysql:5.7
    ports:
      - '0.0.0.0:3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    #    volumes:
#      - mysql:/var/lib/mysql
    environment:
      # 环境变量
      - MYSQL_ROOT_PASSWORD= 123456